name: Branches

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  check-base-branch:
    name: Check Base
    runs-on: ubuntu-latest
    steps:
      - name: Branch is related to CI and is based on main
        if: ${{ startsWith(github.head_ref, 'ci/') && github.base_ref == 'main' }}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          echo "Current base branch: $BASE_BRANCH"
          echo "Branch rule exception: Continuous Integration branches allowed to be merged into main"
      - name: Branch is develop being merged to main for release
        if: ${{ github.base_ref == 'main' && github.head_ref == 'develop' }}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          echo "Current base branch: $BASE_BRANCH"
          echo "Branch rule exception: Develop branch is being merged into main"
      - name: Branch is not based on develop
        if: ${{ github.base_ref != 'develop' && github.head_ref != 'develop' && !startsWith(github.head_ref, 'ci/') }}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          echo "Current base branch: $BASE_BRANCH"
          echo "PRs should only ever be merged into develop"
          exit 1
      - name: Branch verified as based on develop branch
        if: ${{ github.base_ref == 'develop' && github.head_ref != 'develop' && !startsWith(github.head_ref, 'ci/') }}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          echo "Branch is correctly branched off of valid base branch to merge PRs into: $BASE_BRANCH"
